CREATE TABLE  "EXT_CMWBT0011" 
   (	"TOEPASSINGOMGEVING" VARCHAR2(600 CHAR), 
	"STATUS_TOEPASSINGOMGEVING" VARCHAR2(600 CHAR), 
	"CMDB_REFERENTIE_OMGEVING" VARCHAR2(600 CHAR), 
	"VERSIE" VARCHAR2(600 CHAR), 
	"TYPE_OMGEVING" VARCHAR2(250 CHAR), 
	"DATUM_IN_GEBRUIK" VARCHAR2(500 CHAR), 
	"DATUM_BUITEN_GEBRUIK" VARCHAR2(100 CHAR), 
	"CMDB_REFERENTIE_BEDRIJFSTOEPAS" VARCHAR2(600 CHAR), 
	"NAAM_BEDRIJFSTOEPASSING" VARCHAR2(600 CHAR), 
	"NUMMER_BEDRIJFSTOEPASSING" VARCHAR2(600 CHAR), 
	"DIENSTENTYPE" VARCHAR2(600 CHAR), 
	"FINANCIEEL_BEHEERDER_BELEIDSD" VARCHAR2(600 CHAR), 
	"FINANCIEEL_BEHEERDER_ENTITEIT" VARCHAR2(600 CHAR), 
	"EIGENAAR_BELEIDSDOMEIN" VARCHAR2(600 CHAR), 
	"EIGENAAR_ENTITEIT" VARCHAR2(600 CHAR), 
	"STATUS_BEDRIJFSTOEPASSING" VARCHAR2(600 CHAR), 
	"SO_TOEPASSINGSMANAGERS" VARCHAR2(600 CHAR), 
	"VO_APPLICATIEBEHEERDERS" VARCHAR2(600 CHAR), 
	"RELATIE" VARCHAR2(100 CHAR), 
	"CI_CATEGORIE" VARCHAR2(600 CHAR), 
	"CI_TYPE" VARCHAR2(600 CHAR), 
	"CI_CMDB_REFERENTIE" VARCHAR2(600 CHAR), 
	"CI_SYSTEEMNAAM" VARCHAR2(600 CHAR), 
	"CI_STATUS" VARCHAR2(600 CHAR), 
	"CI_EIGENAAR" VARCHAR2(600 CHAR), 
	"PRODUCENT" VARCHAR2(600 CHAR), 
	"PRODUCT" VARCHAR2(600 CHAR), 
	"SW_VERSIE" VARCHAR2(600 CHAR), 
	"OS" VARCHAR2(600 CHAR), 
	"VERSIE_OS" VARCHAR2(600 CHAR), 
	"HWSW" VARCHAR2(100 CHAR), 
	"LOCATIE" VARCHAR2(600 CHAR), 
	"KENMERKEN" VARCHAR2(2000 CHAR), 
	"DIENST_SLA" VARCHAR2(2000 CHAR), 
	"TP_FINANCIEEL_BEHEERDER" VARCHAR2(600 CHAR), 
	"UITDOVEND_DATUM" VARCHAR2(100 CHAR), 
	"UITGEDOOFD_DATUM" VARCHAR2(100 CHAR), 
	"OMGEVING" VARCHAR2(100 CHAR)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CONCESSIE_IN"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY 0X'0A' CHARACTERSET WE8MSWIN1252
        SKIP 1
        FIELDS TERMINATED BY 0X'09' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES are null
            )
      LOCATION
       ( 'CMWBT0011_OR_Inventaris_HW-SW_configuratie_per_toepassingomgeving.csv'
       )
    )
   REJECT LIMIT UNLIMITED
/

 

