CREATE TABLE  "CMWBT0011" 
   (	"ID" NUMBER, 
	"TOEPASSINGOMGEVING" VARCHAR2(255), 
	"STATUS_TOEPASSINGOMGEVING" VARCHAR2(255), 
	"CMDB_REFERENTIE_OMGEVING" NUMBER, 
	"VERSIE" VARCHAR2(255), 
	"TYPE_OMGEVING" VARCHAR2(1), 
	"DATUM_IN_GEBRUIK" DATE, 
	"DATUM_BUITEN_GEBRUIK" VARCHAR2(30), 
	"CMDB_REFERENTIE_BEDRIJFSTOEPAS" NUMBER, 
	"NAAM_BEDRIJFSTOEPASSING" VARCHAR2(255), 
	"NUMMER_BEDRIJFSTOEPASSING" NUMBER, 
	"DIENSTENTYPE" VARCHAR2(255), 
	"FINANCIEEL_BEHEERDER_BELEIDSD" VARCHAR2(255), 
	"FINANCIEEL_BEHEERDER_ENTITEIT" VARCHAR2(255), 
	"EIGENAAR_BELEIDSDOMEIN" VARCHAR2(255), 
	"EIGENAAR_ENTITEIT" VARCHAR2(255), 
	"STATUS_BEDRIJFSTOEPASSING" VARCHAR2(255), 
	"BT_DATUM_IN_GEBRUIK" DATE, 
	"BT_DATUM_BUITEN_GEBRUIK" VARCHAR2(30), 
	"SO_TOEPASSINGSMANAGERS" VARCHAR2(255), 
	"VO_APPLICATIEBEHEERDERS" VARCHAR2(255), 
	"RELATIE" VARCHAR2(30), 
	"CI_CATEGORIE" VARCHAR2(255), 
	"CI_TYPE" VARCHAR2(255), 
	"CI_CMDB_REFERENTIE" NUMBER, 
	"CI_SYSTEEMNAAM" VARCHAR2(255), 
	"CI_STATUS" VARCHAR2(255), 
	"CI_EIGENAAR" VARCHAR2(255), 
	"PRODUCENT" VARCHAR2(255), 
	"PRODUCT" VARCHAR2(255), 
	"SW_VERSIE" VARCHAR2(255), 
	"OS" VARCHAR2(255), 
	"VERSIE_OS" VARCHAR2(255), 
	"HWSW" VARCHAR2(30), 
	"LOCATIE" VARCHAR2(255), 
	"KENMERKEN" VARCHAR2(1000), 
	"DIENST_SLA" VARCHAR2(1000), 
	"TP_FINANCIEEL_BEHEERDER" VARCHAR2(255), 
	"UITDOVEND_DATUM" VARCHAR2(30), 
	"UITGEDOOFD_DATUM" VARCHAR2(30), 
	"OMGEVING" VARCHAR2(30), 
	 CONSTRAINT "CMWBT0011_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "bi_CMWBT0011" 
  before insert on "CMWBT0011"              
  for each row 
begin  
  if :new."ID" is null then
    select "CMWBT0011_SEQ".nextval into :new."ID" from dual;
  end if;
end;
/
ALTER TRIGGER  "bi_CMWBT0011" ENABLE;

