CREATE TABLE  "COMPONENT" 
   (	"ID" NUMBER, 
	"CMDB_ID" NUMBER, 
	"BT_NUMMER" VARCHAR2(255), 
	"CI_CATEGORIE" VARCHAR2(255), 
	"CI_CLASS" VARCHAR2(255), 
	"CI_TYPE" VARCHAR2(255), 
	"DATUM_BUITEN_GEBRUIK" VARCHAR2(255), 
	"DATUM_IN_GEBRUIK" VARCHAR2(255), 
	"DIENSTENTYPE" VARCHAR2(255), 
	"EIGENAAR_BELEIDSDOMEIN" VARCHAR2(255), 
	"EIGENAAR_ENTITEIT" VARCHAR2(255), 
	"FIN_BELEIDSDOMEIN" VARCHAR2(255), 
	"FIN_ENTITEIT" VARCHAR2(255), 
	"HW_SW_FLAG" VARCHAR2(255), 
	"LOCATIE" VARCHAR2(255), 
	"NAAM" VARCHAR2(255), 
	"OMGEVING" VARCHAR2(255), 
	"OS" VARCHAR2(255), 
	"OS_VERSIE" VARCHAR2(255), 
	"PRODUCENT" VARCHAR2(255), 
	"PRODUCT" VARCHAR2(255), 
	"SO_TOEPASSINGSMANAGER" VARCHAR2(255), 
	"STATUS" VARCHAR2(255), 
	"VERSIE" VARCHAR2(255), 
	"VO_APPLICATIEBEHEERDER" VARCHAR2(255), 
	"KENMERKEN" VARCHAR2(1000), 
	"UITDOVEND_DATUM" DATE, 
	"UITGEDOOFD_DATUM" DATE, 
	 CONSTRAINT "COMPONENT_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "bi_COMPONENT" 
  before insert on "COMPONENT"              
  for each row 
begin  
  if :new."ID" is null then
    select "COMPONENT_SEQ".nextval into :new."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "bi_COMPONENT" ENABLE;

