CREATE TABLE  "RELATIONS" 
   (	"ID" NUMBER, 
	"CMDB_ID_SOURCE" NUMBER, 
	"NAAM_SOURCE" VARCHAR2(255), 
	"CI_TYPE_SOURCE" VARCHAR2(255), 
	"CI_CATEGORIE_SOURCE" VARCHAR2(255), 
	"RELATION" VARCHAR2(255), 
	"CMDB_ID_TARGET" NUMBER, 
	"NAAM_TARGET" VARCHAR2(255), 
	"CI_TYPE_TARGET" VARCHAR2(255), 
	"CI_CATEGORIE_TARGET" VARCHAR2(255), 
	 CONSTRAINT "RELATIONS_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "bi_RELATIONS" 
  before insert on "RELATIONS"              
  for each row 
begin  
  if :new."ID" is null then
    select "RELATIONS_SEQ".nextval into :new."ID" from sys.dual;
  end if;
end;
/
ALTER TRIGGER  "bi_RELATIONS" ENABLE;

