perl dc_get_config.pl -e -f -g -b 4
perl dc_get_config.pl -e -f -g -b 126
perl dc_get_config.pl -e -f -g -b 132
perl dc_get_config.pl -e -f -g -b 211
perl dc_get_config.pl -e -f -g -b 321
perl dc_get_config.pl -e -f -g -b 350
perl dc_get_config.pl -e -f -g -b 527
perl dc_get_config.pl -e -f -g -b 585
perl dc_get_config.pl -e -f -g -b 781
perl dc_get_config.pl -e -f -g -b 1350
perl dc_get_config.pl -e -f -g -b 1355
perl dc_get_config.pl -e -f -g -b 1501
perl dc_get_config.pl -e -f -g -b 1742
perl dc_get_config.pl -e -f -g -b 2041
perl dc_get_config.pl -e -f -g -b 2602
perl dc_get_config.pl -e -f -g -b 2861
perl dc_get_config.pl -e -f -g -b 2881
perl dc_get_config.pl -e -f -g -b 2941
