perl get_config.pl -e -f -g -b 365
perl get_config.pl -e -f -g -b 348
perl get_config.pl -e -f -g -b 343
perl get_config.pl -e -f -g -b 76
perl get_config.pl -e -f -g -b 114
perl get_config.pl -e -f -g -b 498
perl get_config.pl -e -f -g -b 526
perl get_config.pl -e -f -g -b 461
perl get_config.pl -e -f -g -b 205
perl get_config.pl -e -f -g -b 168
perl get_config.pl -e -f -g -b 356
perl get_config.pl -e -f -g -b 701
perl get_config.pl -e -f -g -b 326
perl get_config.pl -e -f -g -b 540
perl get_config.pl -e -f -g -b 457
perl get_config.pl -e -f -g -b 127
perl get_config.pl -e -f -g -b 123
perl get_config.pl -e -f -g -b 107
perl get_config.pl -e -f -g -b 124
perl get_config.pl -e -f -g -b 881
perl get_config.pl -e -f -g -b 722
perl get_config.pl -e -f -g -b 841
perl get_config.pl -e -f -g -b 1421
perl get_config.pl -e -f -g -b 1422
perl get_config.pl -e -f -g -b 1561
perl get_config.pl -e -f -g -b 138
perl get_config.pl -e -f -g -b 221
perl get_config.pl -e -f -g -b 94
perl get_config.pl -e -f -g -b 175
perl get_config.pl -e -f -g -b 183
perl get_config.pl -e -f -g -b 424
perl get_config.pl -e -f -g -b 164
perl get_config.pl -e -f -g -b 7
perl get_config.pl -e -f -g -b 741
perl get_config.pl -e -f -g -b 781
perl get_config.pl -e -f -g -b 1004
perl get_config.pl -e -f -g -b 1355
perl get_config.pl -e -f -g -b 92
perl get_config.pl -e -f -g -b 176
perl get_config.pl -e -f -g -b 444
perl get_config.pl -e -f -g -b 152
perl get_config.pl -e -f -g -b 681
perl get_config.pl -e -f -g -b 801
perl get_config.pl -e -f -g -b 571
perl get_config.pl -e -f -g -b 286
perl get_config.pl -e -f -g -b 100
perl get_config.pl -e -f -g -b 353
